class Register < SitePrism::Page
  set_url "index.php?controller=authentication&back=my-account#account-creation"
  element :mr_radio, "#id_gender1"
  element :mrs_radio, "#id_gender2"
  element :customer_first_name_input, "#customer_firstname"
  element :customer_last_name_input, "#customer_lastname"
  element :email_input, "#email"
  element :password_input, "#passwd"
  element :day_select, "#days"
  element :month_select, "#months"
  element :year_select, "#years"
  element :first_name_input, "#firstname"
  element :last_name_input, "#lastname"
  element :company_input, "#company"
  element :address1_input, "#address1"
  element :address2_input, "#address2"
  element :city_input, "#city"
  element :state_select, "#id_state"
  element :zip_code_input, "#postcode"
  element :county_select, "#id_country"
  element :add_information_textarea, "#other"
  element :home_phone_input, "#phone"
  element :cell_phone_input, "#phone_mobile"
  element :additional_email_input, "#alias"
  element :register_button, "#submitAccount"
end
